name: Build Spring Boot EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
    - name: 🧾 Checkout Source Code
      uses: actions/checkout@v4

    - name: ☕ Set up Java 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: 🧪 Build Spring Boot fat JAR
      run: mvn clean package -DskipTests

    - name: 📂 Verify JAR Contents (debug step)
      run: |
        jar tf target/springboot-to-exe-0.0.1-SNAPSHOT.jar | findstr JarLauncher
      shell: cmd

    - name: 📦 Package EXE with jpackage (no main-class)
      run: |
        jpackage --type app-image `
                 --input target `
                 --name MySpringApp `
                 --main-jar springboot-to-exe-0.0.1-SNAPSHOT.jar `
                 --dest output `
                 --java-options "-Xmx512m -Dlogging.file=app.log" `
                 --win-console `
                 --verbose
      shell: powershell

    - name: 📤 Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        n
