name: Build Native Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK and GraalVM
      uses: actions/setup-java@v3
      with:
        java-version: '17' # Or your desired Java version
        distribution: 'graalvm'

    - name: Build Native Executable
      run: mvn clean package -Pnative

    - name: Upload Native Executable
      uses: actions/upload-artifact@v3
      with:
        name: spring-boot-native-executable
        path: target/*.exe # Adjust path based on your project and OS
