name: Build EXE with jpackage

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Download WiX Toolset v3.11.2
      run: |
        Invoke-WebRequest -Uri https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip -OutFile wix.zip
        Expand-Archive wix.zip -DestinationPath wix
        $env:Path += ";$pwd\wix"
        echo "WiX tools manually extracted and added to PATH"
      shell: powershell

    - name: Build Spring Boot fat JAR
      run: mvn clean package -DskipTests

    - name: Create EXE with jpackage
      run: |
        $env:Path += ";$pwd\wix"
        jpackage --type exe `
                 --input target `
                 --name MySpringApp `
                 --main-jar springboot-to-exe-0.0.1-SNAPSHOT.jar `
                 --main-class org.springframework.boot.loader.JarLauncher `
                 --dest output `
                 --win-console `
                 --java-options "-Xmx512m"
      shell: powershell

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: springboot-windows-installer
        path: output\MySpringApp-*.exe
