name: Build Spring Boot EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Build fat JAR with Maven
      run: mvn clean package -DskipTests

    - name: Package EXE with jpackage
      run: |
        jpackage --type app-image `
                 --input target `
                 --name MySpringApp `
                 --main-jar springboot-to-exe-0.0.1-SNAPSHOT.jar `
                 --main-class org.springframework.boot.loader.JarLauncher `
                 --dest output `
                 --java-options "-Xmx512m -Dlogging.file=app.log" `
                 --win-console
      shell: powershell

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: springboot-exe-folder
        path: output\MySpringApp
