name: Build EXE using jpackage

on:
  push:
    branches: [main]

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests

      - name: Install WiX Toolset
        run: choco install wixtoolset

      - name: Create EXE using jpackage
        run: |
          jpackage ^
            --input target ^
            --name MySpringApp ^
            --main-jar springboot-to-exe-0.0.1-SNAPSHOT.jar ^
            --main-class org.springframework.boot.loader.JarLauncher ^
            --type exe ^
            --dest output ^
            --win-console ^
            --java-options "--enable-preview"

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-exe
          path: output/*.exe
