name: Build EXE from Spring Boot App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make Maven Wrapper Executable (for UNIX compatibility, safe on Windows)
        run: chmod +x mvnw

      - name: Build Spring Boot JAR
        run: ./mvnw clean package -DskipTests

      - name: Create Output Directory
        run: mkdir output

      - name: Package EXE using jpackage with console
        run: |
          jpackage `
            --input target `
            --name MySpringApp `
            --main-jar springboot-to-exe-0.0.1-SNAPSHOT.jar `
            --type exe `
            --dest output `
            --win-console `
            --java-options "--enable-preview"

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MySpringApp-Installer
          path: output/
