name: Build Spring Boot EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Create EXE using jpackage
        run: |
          mkdir output
          jpackage `
            --type exe `
            --input target `
            --name MySpringBootApp `
            --main-jar target\my-spring-boot-app-0.0.1-SNAPSHOT.jar `
            --main-class org.springframework.boot.loader.JarLauncher `
            --dest output `
            --java-options "-Xmx512m" `
            --win-console
        shell: pwsh

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-exe
          path: output/
