name: Build Spring Boot EXE Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 🧾 Checkout Code
      uses: actions/checkout@v4

    - name: ☕ Set up Java 21
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: 📥 Download & Install WiX Toolset Manually
      run: |
        Invoke-WebRequest -Uri https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip -OutFile wix.zip
        Expand-Archive -Path wix.zip -DestinationPath wix
        echo "$PWD\wix" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: powershell

    - name: 🧪 Build Spring Boot fat JAR
      run: mvn clean package -DskipTests

    - name: 📦 Package Standalone EXE with jpackage
      run: |
        jpackage --type exe `
                 --input target `
                 --name MySpringApp `
                 --main-jar springboot-to-exe-0.0.1-SNAPSHOT.jar `
                 --dest output `
                 --java-options "-Xmx512m -Dlogging.file=app.log" `
                 --win-console `
                 --verbose
      shell: powershell

    - name: 📤 Upload EXE Installer
      uses: actions/upload-artifact@v4
      with:
        name: springboot-installer
        path: output/MySpringApp-1.0.exe
